### ISSUE TITLE
Feature request: push insight events for quiet down mode, number of agents connected

### ISSUE THREAD

**Issue by dalvizu** [newrelic/nr-jenkins-plugin#11]
Two very important things for me to alert on are whether our Jenkins is stuck in 'quiet down mode', and if there are no ephemeral agents connected.

It would be nice to be able to push this data up to NR insights, so that I can build alerts on it

**Comment by KvistA-ELS** [comment]
Is there a reason for this just is being ignored/nothing happens? I think the idea is really good and I'd like to extend this to send more information - like queue as well. But I don't wanna start working on it if ain't going anywhere...

@dalvizu @sdewitt-newrelic @sschwartzman

**Comment by sdewitt-newrelic** [comment]
@KvistA-ELS I did have a look a bit ago at #12 but I wasn't really fond of the implementation.  I was going to make comments on the PR but haven't been able to get to it.  I will try to get back to looking at it.

**Comment by dalvizu** [comment]
Hi @sdewitt-newrelic is there anything you'd like to see improved on the PR to make it more suitable for a merge?
