### ISSUE TITLE
Feature request: support Jenkinsfile

### ISSUE THREAD

**Issue by dalvizu** [newrelic/nr-jenkins-plugin#13]
We use Jenkinsfile for our projects and would have loved to use this plugin to add deployment markers. However, this isn't an option for us, as we can't add the Publisher to our build.

**Comment by hatless** [comment]
Yes, this. The APM deployment marker post-step needs to be exposed as a Pipeline step. The old community Jenkins plugin for APM deployment markers also lacked support for this. Freestyle jobs and creating jobs in the Jenkins GUI aren't where things are at these days.

**Comment by ghost** [comment]
+1 This feature would be very useful

**Comment by smadduru** [comment]
Any progress on this feature yet ?

**Comment by tim-bezhashvyly** [comment]
+1. I would like send Deployment notifications only for specific branches and currently I don't see such a possibility.

**Comment by OscarNeira** [comment]
+1

**Comment by C-Kenny** [comment]
Also would love to see this implemented here.

**Comment by visdmin** [comment]
+1
