### ISSUE TITLE
Support standard Jenkins plugin install method and JCasC

### ISSUE THREAD

**Issue by neilhwatson** [newrelic/nr-jenkins-plugin#14]
This plugin should be available via the standard Jenkins plugin repo without requiring a separate download. Also support JSacC installation.

**Comment by aries-zhang** [comment]
Agree, I would be able to build my Jenkins master image with below Dockerfile if this plugin were able to be installed from plugin repo.

```
FROM jenkins/jenkins:latest
ARG CURL_OPTIONS
RUN /usr/local/bin/install-plugins.sh blueocean:1.24.4 newrelic:latetst
```

**Comment by aries-zhang** [comment]
From https://www.jenkins.io/doc/developer/publishing/requesting-hosting/, it looks like not too complicated, however, it requires the project to be forked into [jenkinsci](https://github.com/jenkinsci).

Would be nice to know if it's a big no, or there is hope ? @sdewitt-newrelic
