### ISSUE TITLE
How to change Endpoint to EU to forward events 

### ISSUE THREAD

**Issue by ChennaiTechie** [newrelic/nr-jenkins-plugin#37]
By default event is sent us my API key is from EU endpoint how do I change it 

Sending 4 events
Mar 05, 2021 4:53:29 PM FINER com.newrelic.experts.client.internal.NewRelicApiHelper post
ENTRY https://insights-collector.newrelic.com/v1/accounts/#accountID/events
Mar 05, 2021 4:53:29 PM FINEST com.newrelic.experts.client.internal.NewRelicApiHelper
Creating client with URL https://insights-collector.newrelic.com/v1/accounts/#accountID/events
Mar 05, 2021 4:53:29 PM FINEST com.newrelic.experts.client.internal.NewRelicApiHelper
Posting to https://insights-collector.newrelic.com/v1/accounts/#accountID/events
Mar 05, 2021 4:53:29 PM SEVERE com.newrelic.experts.client.internal.NewRelicApiHelper post
The HTTP post failed with status code HTTP/1.1 403 Forbidden
Mar 05, 2021 4:53:29 PM SEVERE com.newrelic.experts.client.internal.NewRelicApiHelper post
The HTTP post failed with exception: com.newrelic.experts.client.api.NewRelicClientException
Mar 05, 2021 4:53:29 PM FINER com.newrelic.experts.client.internal.NewRelicApiHelper post
RETURN

**Comment by nikhilkumarmm** [comment]
@sdewitt-newrelic  I can see the same problem , by default it is generating the  https://insights-collector.newrelic.com/v1/accounts/#accountID/events
how we can change it to EU one. 
like https://insights-collector.eu01.nr-data.net
