### ISSUE TITLE
Hi could you help me with error please 

### ISSUE THREAD

**Issue by emelianrus** [newrelic/nr-jenkins-plugin#6]
SEVERE: Timer task com.newrelic.experts.jenkins.extensions.EventCollectorWork@389c1d64 failed
java.lang.ArrayIndexOutOfBoundsException

**Comment by ipleten** [comment]
Looks like that error lead to memory leak.
Could please some take a look? Should we escalate via our account to support directly?

**Comment by sdewitt-newrelic** [comment]
Hi @emelianrus and @ipleten I apologize for the delay!  Can you please provide me additional information such as a full log, OS type/version, Jenkins version, build type, etc?

**Comment by sdewitt-newrelic** [comment]
Closing issue due to lack of response.
